[package]
name = "panic-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.95"
autocxx = "0.25.0"

[build-dependencies]
autocxx-build = "0.25.0"
